auth_enabled: false

server:
  http_listen_port: 3100
  log_level: info
  grpc_server_max_recv_msg_size: 10485760 # Maximum gRPC receive message size
  grpc_server_max_send_msg_size: 10485760 # Maximum gRPC send message size
  grpc_listen_port: 9096

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory # Use "memberlist" or "consul" for HA setups
      replication_factor: 1 # Set to >1 for redundancy in HA setups
  chunk_idle_period: 5m       # Duration after which inactive chunks are flushed
  chunk_retain_period: 30s    # Retention time for old chunks before flushing
  max_transfer_retries: 20    # Retry attempts for chunk transfers in HA setups

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h # Maximum age of logs accepted (7 days)
  max_streams_per_user: 0         # No limit on streams per user

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index # Active index directory
    shared_store: filesystem # Shared storage backend for indexes
    cache_location: /loki/cache # Cache directory for boltdb
  filesystem:
    directory: /loki/chunks

compactor:
  working_directory: /loki/compactor # Compactor's working directory
  shared_store: filesystem # Shared storage backend for compactor

table_manager:
  retention_deletes_enabled: true # Enable log retention
  retention_period: 168h         # Retain logs for 7 days

ruler:
  storage:
    type: local
    local:
      directory: /loki/rules # Directory for rule files
  rule_path: /loki/rules # Path to rules
  enable_api: true # Enable the Ruler API

schema_config:
  configs:
    - from: 2022-01-01
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h
