auth_enabled: false

server:
  http_listen_port: 3100
  log_level: info
  grpc_server_max_recv_msg_size: 10485760 # Maximum gRPC receive message size
  grpc_server_max_send_msg_size: 10485760 # Maximum gRPC send message size
  grpc_listen_port: 9096

ingester:
  lifecycler:
    ring:
      instance_addr: 127.0.0.1
      kvstore:
        store: inmemory # Use "memberlist" or "consul" for HA setups
      replication_factor: 1 # Set to >1 for redundancy in HA setups
    final_sleep: 0s
  chunk_idle_period: 5m       # Duration after which inactive chunks are flushed
  chunk_retain_period: 30s    # Retention time for old chunks before flushing
  chunk_block_size: 262144    # Block size for chunks
  chunk_encoding: snappy
  chunk_target_size: 1572864

limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 168h # Maximum age of logs accepted (7 days)
  max_streams_per_user: 0         # No limit on streams per user

storage_config:
  tsdb:
    block_ranges_period: 2h          # Default block range duration
    retention_period: 168h           # Retain data for 7 days
    cache_location: /loki/cache      # Cache for indexes and other metadata
    head_chunk_timeout: 1h           # How long TSDB keeps chunks in memory
  filesystem:
    directory: /loki/chunks          # Directory for chunk storage


compactor:
  working_directory: /loki/compactor # Compactor's working directory
  shared_store: filesystem

#table_manager:
#  retention_deletes_enabled: true
#  retention_period: 168h # Retain data for 7 days

ruler:
  storage:
    type: local
    local:
      directory: /loki/rules # Directory for rule files
  rule_path: /loki/rules # Path to rules
  enable_api: true # Enable the Ruler API

schema_config:
  configs:
    - from: 2022-01-01
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h
