server:
  http_listen_port: 9080
  grpc_listen_port: 0

clients:
  - url: http://localhost:3100/loki/api/v1/push

positions:
  filename: /tmp/positions.yaml

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          environment: system
          service: system
          __path__: /var/log/**/*.log
  - job_name: dungeon-prototype-app-prod
    static_configs:
      - targets:
          - localhost
        labels:
          job: springboot
          environment: production
          service: dungeon-prototype-app
          __path__: /logs/dungeon-prototype-prod.log
