global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'kafka'
    static_configs:
      - targets: ['jmx-exporter:7071']

  - job_name: 'prod-dungeon-prototype-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['prod-dungeon-prototype-app:8080']
      - labels:
          application: 'dungeon-prototype-app'
          instance: 'prod'

  - job_name: 'dev-dungeon-prototype-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'dev-dungeon-prototype-app:8081' ]
      - labels:
          application: 'dungeon-prototype-app'
          instance: 'dev'

  - job_name: 'test-dungeon-prototype-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'test-dungeon-prototype-app:8081' ]
      - labels:
          application: 'dungeon-prototype-app'
          instance: 'test'

  - job_name: 'loki'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['loki:3100']

  - job_name: 'mongodb'
    metrics_path: '/metrics'
    static_configs:
      - targets: [ 'mongodb-exporter:9216' ]

  - job_name: 'mongodb-percona'
    metrics_path: '/metrics'
    static_configs:
      - targets: [ 'mongodb-exporter-percona:9001' ]

  - job_name: 'prometheus'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['prometheus:9090']
