global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:7071', 'kafka:9998']

  - job_name: 'cryostat-jfr-metrics'
    metrics_path: '/api/v2/targets/__meta_cryostat_target_connectUrl__/metrics'
    scheme: 'http'
    http_sd_configs:
      - url: 'http://cryostat:8181/api/v2/discovery'
        refresh_interval: 30s
    relabel_configs:
      - source_labels: [ __meta_cryostat_target_connectUrl ]
        target_label: connectUrl
      - source_labels: [ __meta_cryostat_target_connectUrl ]
        regex: '(.*)'
        replacement: '${1}'
        target_label: __metrics_path__


  - job_name: 'prod-dungeon-prototype-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['prod-dungeon-prototype-app:8080']
      - labels:
          application: 'dungeon-prototype-app'
          instance: 'prod'

  - job_name: 'dev-dungeon-prototype-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'dev-dungeon-prototype-app:8081' ]
      - labels:
          application: 'dungeon-prototype-app'
          instance: 'dev'

  - job_name: 'test-dungeon-prototype-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'test-dungeon-prototype-app:8082' ]
      - labels:
          application: 'dungeon-prototype-app'
          instance: 'test'

  - job_name: 'loki'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['loki:3100']

  - job_name: 'mongodb'
    metrics_path: '/metrics'
    static_configs:
      - targets: [ 'mongodb-exporter:9001' ]

  - job_name: 'prometheus'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['prometheus:9090']
