server:
  http_listen_port: 9080
  grpc_listen_port: 0

clients:
  - url: http://loki:3100/loki/api/v1/push

positions:
  filename: /tmp/positions.yaml

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          environment: system
          service: system
          __path__: /var/log/**/*.log
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - target_label: thread
      - source_labels: [thread]
      # Extract container labels into Loki labels
      - source_labels: [__meta_docker_container_label_environment]
        target_label: environment
      - source_labels: [__meta_docker_container_label_service]
        target_label: service
      # Use container name as job label
      - source_labels: [__meta_docker_container_name]
        target_label: job
      # Remove internal Docker Compose metadata
      - source_labels: [__meta_docker_container_label_com_docker_compose_service]
        target_label: __discarded__

    pipeline_stages:
      - docker: {}
