global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'springboot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:9091']

  - job_name: 'loki'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['localhost:3100']

  - job_name: 'mongodb'
    static_configs:
      - targets: [ 'localhost:9216' ]

  - job_name: 'prometheus'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['localhost:9090']
