global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'dungeon-prototype-app-prod'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['prod-dungeon-prototype-app:8080']

  - job_name: 'dungeon-prototype-app-dev'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'dev-dungeon-prototype-app:8081' ]

  - job_name: 'loki'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['loki:3100']

  - job_name: 'mongodb'
    static_configs:
      - targets: [ 'localhost:9216' ]

  - job_name: 'prometheus'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['prometheus:9090']
