spring:
  datasource:
    url: jdbc:postgresql://localhost:${POSTGRES_DATABASE_PORT}/${POSTGRES_DATABASE_NAME}
    name: ${POSTGRES_DATABASE_NAME}
    username: ${POSTGRES_DATABASE_USER}
    password: ${POSTGRES_DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 60000

  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
      port: ${SPRING_DATA_MONGO_DB_PORT}
      database: ${SPRING_DATA_MONGODB_DATABASE}
      username: ${SPRING_DATA_MONGODB_USERNAME}
      password: ${SPRING_DATA_MONGODB_PASSWORD}
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  profiles:
    active: ${SPRING_ACTIVE_PROFILE}

management:
  endpoints:
    web:
      exposure:
        include: prometheus
      base-path: /actuator
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      prometheus:
        enabled: true
    endpoint:
      prometheus:
        enabled: true


server:
  port: ${BOT_WEBHOOK_PORT}

bot:
  username: ${BOT_USERNAME}
  path: ${BOT_WEBHOOK_PATH}
  webhook: ${BOT_WEBHOOK_URL}
  token: ${BOT_AUTH_TOKEN}
  auth-users: ${AUTH_USERS}
  files:
    images: ${IMAGE_PATH}

kafka-topics:
  item-naming-topic: ${ITEM_NAMING_TOPIC}

messaging:
  bar-blocks: 6
  xp-bar-blocks: 10
  stat-bar-blocks: 10
  constants:
    emoji:
      treasure: "\uD83D\uDCB0"
      heart: "\uD83D\uDC9F"
      red-square: "\uD83D\uDFE5"
      diamond: "\uD83D\uDC8E"
      blue-square: "\uD83D\uDFE6"
      black-heart: "🖤"
      sword: "\uD83D\uDDE1"
      dagger: "🔪"
      shield: "\uD83D\uDEE1"
      stonks: "\uD83D\uDCC8"
      brown-block: "\uD83D\uDFEB"
      orange-block: "🟧"
      axe: "\uD83E\uDE93"

  keyboard:
    buttons:
      bot-start:
        callback: /start
      start-game:
        callback: btn_start_game
        name: Start Game
      continue-game:
        callback: btn_continue_game
        name: Continue Game
      next-level:
        callback: btn_next_level
        name: Next Level
      left:
        callback: btn_left
        name: Left
      right:
        callback: btn_right
        name: Right
      forward:
        callback: btn_forward
        name: Forward
      back:
        callback: btn_turn_back
        name: Turn Back
      attack:
        callback: btn_attack
        name: ${messaging.constants.emoji.sword} %d
      secondary-attack:
        callback: btn_attack_sec
        name: ${messaging.constants.emoji.dagger} %d
      map:
        callback: btn_map
        name: Map
      player-stats:
        callback: btn_stats
        name: Stats
      menu-back:
        callback: btn_menu_back
        name: Back
      shrine:
        callback: btn_shrine_use
        name: Use
      merchant-buy-menu:
        callback: btn_merchant_buy_menu
        name: Buy items!
      merchant-buy-menu-back:
        callback: btn_merchant_buy_menu
        name: Back
      merchant-sell-menu:
        callback: btn_merchant_sell_menu
        name: Sell items!
      merchant-sell-menu-back:
        callback: btn_merchant_sell_menu
        name: Back
      restore-armor:
        callback: btn_restore_armor
        name: Restore Armor
      sharpen-weapon:
        callback: btn_sharpen_weapon
        name: Sharpen Weapon
      treasure-open:
        callback: btn_treasure_open
        name: Open
      treasure-gold-collected:
        callback: btn_treasure_gold_collected
        name: "%d ${messaging.constants.emoji.treasure}"
      treasure-item-collected:
        callback: btn_treasure_item_collected_%s
      treasure-collect-all:
        callback: btn_treasure_collect_all
        name: Collect all
      inventory:
        callback: btn_inventory
        name: Inventory
      head:
        callback: btn_inventory_display_head_%s
      vest:
        callback: btn_inventory_display_vest_%s
      gloves:
        callback: btn_inventory_display_gloves_%s
      boots:
        callback: btn_inventory_display_boots_%s
      right-hand:
        callback: btn_inventory_display_primary_weapon_%s
      left-hand:
        callback: btn_inventory_display_secondary_weapon_%s
      item-inventory:
        callback: btn_inventory_display_item_%s
      item-inventory-back:
        callback: btn_inventory
        name: Back
      item-inventory-equip:
        callback: btn_inventory_item_equip_%s
        name: (equip)
      item-inventory-un-equip:
        callback: btn_inventory_item_un_equip_%s
        name: (un-equip)
      merchant-sell-display-head:
        callback: btn_merchant_display_head_%s
      merchant-sell-display-vest:
        callback: btn_merchant_display_vest_%s
      merchant-sell-display-gloves:
        callback: btn_merchant_display_gloves_%s
      merchant-sell-display-boots:
        callback: btn_merchant_display_boots_%s
      merchant-sell-display-right-hand:
        callback: btn_merchant_display_primary_weapon_%s
      merchant-sell-display-left-hand:
        callback: btn_merchant_display_secondary_weapon_%s
      merchant-sell-display-item:
        callback: btn_merchant_display_item_%s
      merchant-item-sell:
        callback: btn_merchant_list_item_sell_%s
      merchant-item-buy:
        callback: btn_merchant_list_item_buy_%s
      merchant-sell-price:
        callback: btn_merchant_sell_%s
        name: "%d ${messaging.constants.emoji.treasure}"
      merchant-buy-price:
        callback: btn_merchant_buy_%s
        name: "%d ${messaging.constants.emoji.treasure}"
      player-attribute-upgrade:
        callback: btn_player_attribute_upgrade_%s

generation:
  level:
    level-one-grid-size: 10
    grid-size-increment: 1
    increment-step: 10
  monsters:
    zombie:
      primary-attack-type: slash
      secondary-attack-type: slash
    werewolf:
      primary-attack-type: growl
      secondary-attack-type: slash
    swamp-beast:
      primary-attack-type: poison_spit
      secondary-attack-type: bite
    vampire:
      primary-attack-type: vampire_bite
      secondary-attack-type: slash
    dragon:
      primary-attack-type: fire_spit
      secondary-attack-type: growl
  items:
    selling-price-ratio: 0.9
    buying-price-ratio: 1.2
    weapon:
      weapon-attributes-pool-size: 1000
      weapon-per-game: 200
      default-attributes:
        sword:
          attack: 6
          critical-hit-chance: 0.3
          critical-hit-multiplier: 1.2
          chance-to-miss: 0.5
          chance-to-knock-out: 0.0
        axe:
          attack: 8
          critical-hit-chance: 0.3
          critical-hit-multiplier: 1.1
          chance-to-miss: 0.7
          chance-to-knock-out: 0.1
        mace:
          attack: 8
          critical-hit-chance: 0.3
          critical-hit-multiplier: 1.1
          chance-to-miss: 0.6
          chance-to-knock-out: 0.2
        club:
          attack: 8
          critical-hit-chance: 0.2
          critical-hit-multiplier: 1.2
          chance-to-miss: 0.5
          chance-to-knock-out: 0.4
        dagger:
          attack: 4
          critical-hit-chance: 0.4
          critical-hit-multiplier: 1.05
          chance-to-miss: 0.4
          chance-to-knock-out: 0.0
        spear:
          attack: 7
          critical-hit-chance: 0.3
          critical-hit-multiplier: 1.1
          chance-to-miss: 0.6
          chance-to-knock-out: 0.2
        staff:
          attack: 5
          critical-hit-chance: 0.3
          critical-hit-multiplier: 1.3
          chance-to-miss: 0.2
          chance-to-knock-out: 0.0
      handling-adjustment-attributes:
        single-handed:
          attack-ratio: 0.95
          chance-to-miss-ratio: 0.9
          critical-chance-ratio: 1.05
          critical-multiplier-ratio: 1.1
          knock-out-chance-ratio: 1.0
        two-handed:
          attack-ratio: 1.15
          chance-to-miss-ratio: 1.1
          critical-chance-ratio: 0.95
          critical-multiplier-ratio: 1.2
          knock-out-chance-ratio: 1.0
      weapon-material-adjustment-attributes:
        steel:
          attack-ratio: 1.1
          chance-to-miss-ratio: 1.0
          critical-chance-ratio: 1.05
          critical-multiplier-ratio: 1.0
          knock-out-chance-ratio: 1.0
        wood:
          attack-ratio: 1.0
          chance-to-miss-ratio: 1.0
          critical-chance-ratio: 1.0
          critical-multiplier-ratio: 1.05
          knock-out-chance-ratio: 0.9
        stone:
          attack-ratio: 1.2
          chance-to-miss-ratio: 1.0
          critical-chance-ratio: 1.0
          critical-multiplier-ratio: 1.1
          knock-out-chance-ratio: 1.2
        iron:
          attack-ratio: 1.1
          chance-to-miss-ratio: 1.0
          critical-chance-ratio: 1.1
          critical-multiplier-ratio: 1.0
          knock-out-chance-ratio: 1.0
        platinum:
          attack-ratio: 1.0
          chance-to-miss-ratio: 1.0
          critical-chance-ratio: 1.3
          critical-multiplier-ratio: 1.2
          knock-out-chance-ratio: 1.0
        diamond:
          attack-ratio: 1.3
          chance-to-miss-ratio: 1.0
          critical-chance-ratio: 1.3
          critical-multiplier-ratio: 1.3
          knock-out-chance-ratio: 1.0
        mithril:
          attack-ratio: 1.5
          chance-to-miss-ratio: 1.0
          critical-chance-ratio: 1.5
          critical-multiplier-ratio: 1.4
          knock-out-chance-ratio: 1.0
        obsidian:
          attack-ratio: 1.4
          chance-to-miss-ratio: 1.0
          critical-chance-ratio: 1.4
          critical-multiplier-ratio: 1.5
          knock-out-chance-ratio: 1.0
        enchanted-wood:
          attack-ratio: 1.1
          chance-to-miss-ratio: 1.0
          critical-chance-ratio: 1.2
          critical-multiplier-ratio: 1.3
          knock-out-chance-ratio: 1.0
        dragon-bone:
          attack-ratio: 1.3
          chance-to-miss-ratio: 1.0
          critical-chance-ratio: 1.2
          critical-multiplier-ratio: 1.5
          knock-out-chance-ratio: 1.0
      weapon-handler-material-adjustment-attributes:
        wood:
          attack-ratio: 1.0
          chance-to-miss-ratio: 1.0
          critical-chance-ratio: 1.0
          critical-multiplier-ratio: 1.0
          knock-out-chance-ratio: 1.0
        steel:
          attack-ratio: 1.0
          chance-to-miss-ratio: 1.0
          critical-chance-ratio: 1.05
          critical-multiplier-ratio: 1.1
          knock-out-chance-ratio: 1.0
        leather:
          attack-ratio: 1.0
          chance-to-miss-ratio: 0.9
          critical-chance-ratio: 1.1
          critical-multiplier-ratio: 1.0
          knock-out-chance-ratio: 1.0
        treated-leather:
          attack-ratio: 1.0
          chance-to-miss-ratio: 0.6
          critical-chance-ratio: 1.15
          critical-multiplier-ratio: 1.2
          knock-out-chance-ratio: 1.0
        dragon-bone:
          attack-ratio: 1.3
          chance-to-miss-ratio: 1.0
          critical-chance-ratio: 1.2
          critical-multiplier-ratio: 1.3
          knock-out-chance-ratio: 1.0
      complete-material-adjustment-attributes:
        dragon-bone:
          attack-ratio: 1.5
          chance-to-miss-ratio: 0.3
          critical-chance-ratio: 1.7
          critical-multiplier-ratio: 1.6
          knock-out-chance-ratio: 1.0
        wood:
          attack-ratio: 1.0
          chance-to-miss-ratio: 1.0
          critical-chance-ratio: 1.0
          critical-multiplier-ratio: 1.0
          knock-out-chance-ratio: 1.1
        steel:
          attack-ratio: 1.1
          chance-to-miss-ratio: 1.0
          critical-chance-ratio: 1.0
          critical-multiplier-ratio: 1.0
          knock-out-chance-ratio: 1.0
      size-adjustment-attributes:
        small:
          attack-ratio: 0.9
          critical-chance-ratio: 1.0
          critical-multiplier-ratio: 1.0
          chance-to-miss-ratio: 0.8
          knock-out-chance-ratio: 1.0
        medium:
          attack-ratio: 1.0
          critical-chance-ratio: 1.0
          critical-multiplier-ratio: 1.0
          chance-to-miss-ratio: 0.9
          knock-out-chance-ratio: 1.0
        large:
          attack-ratio: 1.2
          critical-chance-ratio: 1.0
          critical-multiplier-ratio: 1.0
          chance-to-miss-ratio: 1.15
          knock-out-chance-ratio: 1.0
      attack-type-adjustment-attributes:
        stab:
          attack-ratio: 1.0
          critical-chance-ratio: 1.3
          critical-multiplier-ratio: 1.0
          chance-to-miss-ratio: 1.0
          knock-out-chance-ratio: 1.0
        slash:
          attack-ratio: 1.2
          critical-chance-ratio: 1.0
          critical-multiplier-ratio: 1.2
          chance-to-miss-ratio: 1.0
          knock-out-chance-ratio: 0.0
        blunt:
          attack-ratio: 1.0
          critical-chance-ratio: 1.0
          critical-multiplier-ratio: 1.0
          chance-to-miss-ratio: 1.0
          knock-out-chance-ratio: 1.4
        strike:
          attack-ratio: 1.0
          knock-out-chance-ratio: 1.0
          critical-multiplier-ratio: 1.0
          chance-to-miss-ratio: 1.0
          critical-chance-ratio: 1.0

      quality-adjustment-ratio:
        common: 0.8
        rare: 1.1
        epic: 1.3
        legendary: 1.4
        mythic: 1.6

    wearables:
      wearable-attribute-pool-size: 150
      wearables-per-game: 100

      default-armor: 5
      chance-to-dodge-ratio:
        cloth: 0.0
        leather: 0.3
        iron: 0.2
        steel: 0.1
        chain-mail: 0.0
        enchanted-leather: 0.3
        treated-leather: 0.4
        mithril: 0.0
        elven-silk: 0.0
        wool: 0.0
      armor-bonus:
        cloth: -2
        leather: -1
        treated-leather: 0
        enchanted-leather: -1
        iron: 2
        steel: 3
        chain-mail: 4
        elven-silk: 0
        mithril: 4
        wool: 0
      quality-adjustment-ratio:
        common: 0.8
        rare: 1.1
        epic: 1.3
        legendary: 1.4
        mythic: 1.6

    effects:
      minimum-amount-per-item-map:
        common: 0
        rare: 1
        epic: 2
        legendary: 3
        mythic: 3
      maximum-amount-per-item-map:
        common: 1
        rare: 2
        epic: 3
        legendary: 3
        mythic: 4

battle:
  player-defense-ratio-matrix:
    slash:
      material-defense-ratio-map:
        iron: 0.7
        steel: 0.8
        mithril: 1.1
    growl:
      material-defense-ratio-map:
        iron: 1.0
        steel: 0.9
        mithril: 0.7
    vampire-bite:
      material-defense-ratio-map:
        cloth: 0.6
        leather: 0.7
        iron: 0.85
        steel: 0.9
        chain-mail: 0.95
        enchanted-leather: 1.2
        treated-leather: 0.8
        mithril: 1.3
    bite:
      material-defense-ratio-map:
        cloth: 0.6
        leather: 0.7
        iron: 1.1
        steel: 1.15
        chain-mail: 1.2
        enchanted-leather: 0.7
        treated-leather: 0.8
        mithril: 1.2
    fire-spit:
      material-defense-ratio-map:
        cloth: 0.3
        leather: 0.35
        iron: 0.7
        steel: 0.8
        chain-mail: 0.85
        enchanted-leather: 0.75
        treated-leather: 0.65
        mithril: 1.1
    poison-spit:
      material-defense-ratio-map:
        cloth: 0.4
        leather: 0.65
        iron: 0.5
        steel: 0.55
        chain-mail: 0.6
        enchanted-leather: 0.8
        treated-leather: 0.7
        mithril: 1.15
  #  TODO: adjust values
  monster-defense-ratio-matrix:
    slash:
      monster-defense-ratio-map:
        dragon: 1.0
        swamp-beast: 1.0
        vampire: 1.0
        werewolf: 1.0
        zombie: 1.0
    strike:
      monster-defense-ratio-map:
        dragon: 1.0
        swamp-beast: 1.0
        vampire: 1.0
        werewolf: 1.0
        zombie: 1.0
    blunt:
      monster-defense-ratio-map:
        dragon: 1.0
        swamp-beast: 1.0
        vampire: 1.0
        werewolf: 1.0
        zombie: 1.0
    stab:
      monster-defense-ratio-map:
        dragon: 1.0
        swamp-beast: 1.0
        vampire: 1.0
        werewolf: 1.0
        zombie: 1.0

player:
  attributes: #TODO: consider different classes
    power: 5
    stamina: 4
    perception: 3
    magic: 1
    luck: 2
  base-hp: 60
  attribute-hp-factor: 10
  base-mana: 6
  attribute-mana-factor: 1
