tunnel: dungeon-bot-prod
credentials-file: /etc/cloudflared/.json

ingress:
  - hostname: dungeonprototypebot.xyz/webhook
    service: http://localhost:8080
  - service: http_status:404  # Default response for non-matching requests
