import os
from dotenv import load_dotenv

load_dotenv()

IMAGE_PATH = os.getenv("IMAGE_PATH")

HF_MODEL_FILE = os.getenv('HUGGINGFACE_MODEL_FILE')
HF_API_KEY = os.getenv('HUGGINGFACE_API_KEY')
MONGO_DATABASE_PORT = os.getenv('MONGO_DB_PORT')
MONGO_DATABASE_NAME = os.getenv('MONGO_DB_DATABASE')
MONGO_DATABASE_USER = os.getenv('MONGO_DB_USERNAME')
MONGO_DATABASE_PASSWORD = os.getenv('MONGO_DB_PASSWORD')

KAFKA_BOOTSTRAP_SERVER = os.getenv("KAFKA_BOOTSTRAP_SERVERS")
KAFKA_BALANCE_MATRIX_TOPIC = os.getenv("KAFKA_BALANCE_MATRIX_TOPIC")
KAFKA_TOPIC_ITEM_NAMING = os.getenv("KAFKA_ITEM_NAMING_TOPIC")
KAFKA_GAME_RESULTS_TOPIC = os.getenv("KAFKA_GAME_RESULTS_TOPIC")

# Directory to store weight vectors for Retrieval-Augmented Generation
RAG_STORE_PATH = os.path.join(HF_MODEL_FILE, "rag_store")
