import os
from dotenv import load_dotenv

load_dotenv()

POSTGRES_USER = os.getenv("POSTGRES_USER")
POSTGRES_PASSWORD = os.getenv("POSTGRES_PASSWORD")
POSTGRES_DB = os.getenv("POSTGRES_DB")
POSTGRES_PORT = os.getenv("POSTGRES_PORT")

HF_MODEL_FILE = os.getenv('HUGGINGFACE_MODEL_FILE')
MONGO_DATABASE_PORT = os.getenv('MONGO_DB_PORT')
MONGO_DATABASE_NAME = os.getenv('MONGO_DB_DATABASE')
MONGO_DATABASE_USER = os.getenv('MONGO_DB_USERNAME')
MONGO_DATABASE_PASSWORD = os.getenv('MONGO_DB_PASSWORD')

KAFKA_BOOTSTRAP_SERVER = os.getenv("KAFKA_BOOTSTRAP_SERVERS")
KAFKA_TOPIC_BALANCES = os.getenv("KAFKA_TOPIC_BALANCES")
KAFKA_TOPIC_ITEM_NAMING = os.getenv("KAFKA_ITEM_NAMING_TOPIC")
