name: Deploy to prod

on:
  push:
    branches: ["master"]

jobs:
  build-and-run:
    runs-on: self-hosted
    if: "!startsWith(github.event.head_commit.message, '[auto] update branch list') && !startsWith(github.event.head_commit.message, '[no-deploy]')"
    environment: prod
    permissions:
      contents: read

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          clean: false
      - name: Check Latest Commit Message
        id: check_commit
        run: |
          set -e
          LATEST_COMMIT_MSG=$(git log -1 --pretty=%B)
          echo "Latest commit message: '$LATEST_COMMIT_MSG'"

          if [[ "$LATEST_COMMIT_MSG" =~ ^\[auto\]\ update\ branch\ list ]]; then
            echo "Skipping redeployment due to automated commit."
            exit 0
          fi
      - name: Set environment variables
        run: |
          echo "ENV=${{vars.ENV}}" >> .env
          echo "JAVA_OPTIONS=${{vars.JAVA_OPTIONS}}" >> .env
          echo "BOT_AUTH_TOKEN=${{ secrets.BOT_TOKEN }}" >> .env
          echo "BOT_USERNAME=${{vars.BOT_USERNAME}}" >> .env
          echo "BOT_WEBHOOK_PORT=${{vars.BOT_WEBHOOK_PORT}}" >> .env
          echo "BOT_WEBHOOK_PATH=${{vars.BOT_WEBHOOK_PATH}}" >> .env
          echo "BOT_WEBHOOK_URL=${{vars.BOT_WEBHOOK_URL}}" >> .env
          echo "GRAFANA_USER=${{secrets.GRAFANA_USER}}" >> .env
          echo "GRAFANA_PASSWORD=${{secrets.GRAFANA_PASSWORD}}" >> .env
          echo "KAFKA_PORT=${{vars.KAFKA_PORT}}" >> .env
          echo "KAFKA_ITEM_NAMING_TOPIC=${{vars.KAFKA_ITEM_NAMING_TOPIC}}" >> .env
          echo "MONGO_DB_DATABASE_NAME=${{vars.MONGO_DB_DATABASE_NAME}}" >> .env
          echo "MONGO_DB_PORT=${{vars.MONGO_DB_PORT}}" >> .env
          echo "MONGO_DB_USER=${{ secrets.MONGO_DB_USER }}" >> .env
          echo "MONGO_DB_PASSWORD=${{ secrets.MONGO_DB_PASSWORD }}" >> .env
      - name: Create shared network
        run: |
            if [ ! "$(docker network ls | grep shared_net)" ]; then
              echo "Creating shared_net network ..."
              docker network create shared_net
            else
              echo "shared_net network exists."
            fi

      - name: Download JMX Exporter JAR
        run: |
          cd jmx-exporter
          wget -q https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/1.0.1/jmx_prometheus_javaagent-1.0.1.jar \
            -O ./jmx_prometheus_javaagent.jar

      - name: Run Shared services
        run: docker-compose -p shared -f docker-compose.shared.yml --env-file .env up --build -d
      - name: Create network
        run: |
          if [ ! "$(docker network ls | grep prod_net)" ]; then
            echo "Creating prod_net network ..."
            docker network create prod_net
          else
            echo "prod_net network exists."
          fi
      - name: Run Environment specific services
        run: docker-compose -p prod --env-file .env up --build -d
      - name: Clean up environment file
        run: rm -f .env
      - name: Cleanup Docker Data
        run: docker system prune -af &&
          docker volume prune -f
      - name: Verify Cleanup
        run: docker system df
