name: Enforce PR Rules

on:
  pull_request:
    types:
      - opened
    branches:
      - master

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Source
        run: |
          if [ [ "${{ github.head_ref }}" != "develop" ] || [ !startsWith( '${{ github.head_ref }}', 'update-branch-list-' ) ]; then
            echo "Pull requests to master are only allowed from develop!";
            exit 1;
          fi
        shell: bash
