name: CI for production

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - uses: Autom3/docker-deployment-action@3.0.0
      with:
        remote_docker_host: ${{ secrets.REMOTE_HOST }}
        ssh-private-key: ${{ secrets.REMOTE_HOST_KEY }}
    - name: Run Docker compose
      uses: Autom3/docker-deployment-action@3.0.1
      with:
        up-flags:
          --build --detach
      env: 
        BOT_AUTH_TOKEN: ${{ secrets.BOT_TOKEN_PROD }}
        BOT_USERNAME: ${{vars.BOT_USERNAME}}
        BOT_WEBHOOK_PORT: ${{vars.BOT_WEBHOOK_PORT}}
        BOT_WEBHOOK_URL: ${{vars.BOT_WEBHOOK_URL}}
        ENV: ${{vars.ENV}}
        KAFKA_BOOTSTRAP_SERVERS: ${{vars.KAFKA_BOOTSTRAP_SERVERS}}
        KAFKA_ITEM_NAMING_TOPIC: ${{vars.KAFKA_ITEM_NAMING_TOPIC}}
        MONGO_DB_DATABASE_NAME: ${{vars.MONGO_DB_DATABASE_NAME}}
        MONGO_DB_URI: ${{vars.MONGO_DB_URI}}
        MONGO_DB_USER: ${{ secrets.MONGO_DB_USER }}
        MONGO_DB_PASSWORD: ${{ secrets.MONGO_DB_PASSWORD }}
