name: CI for production

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-run:
    runs-on: self-hosted
    environment: prod
    permissions:
      contents: read

    steps:
      - name: Update repository
        run : cd ${{vars.WORK_DIR}} && git pull origin master
      - name: Set environment variables
        env:
          ENV: ${{vars.ENV}}
          BOT_AUTH_TOKEN: ${{ secrets.BOT_TOKEN_PROD }}
          BOT_USERNAME: ${{vars.BOT_USERNAME}}
          BOT_WEBHOOK_PORT: ${{vars.BOT_WEBHOOK_PORT}}
          BOT_WEBHOOK_URL: ${{vars.BOT_WEBHOOK_URL}}
          CLOUDFLARE_TOKEN_PROD: ${{secrets.CLOUDFLARE_TOKEN_PROD}}
          KAFKA_BOOTSTRAP_SERVERS: ${{vars.KAFKA_BOOTSTRAP_SERVERS}}
          KAFKA_ITEM_NAMING_TOPIC: ${{vars.KAFKA_ITEM_NAMING_TOPIC}}
          MONGO_DB_DATABASE_NAME: ${{vars.MONGO_DB_DATABASE_NAME}}
          MONGO_DB_URI: ${{vars.MONGO_DB_URI}}
          MONGO_DB_USER: ${{ secrets.MONGO_DB_USER }}
          MONGO_DB_PASSWORD: ${{ secrets.MONGO_DB_PASSWORD }}
        run: |
          cd ${{vars.WORK_DIR}} &&
          echo "ENV=${ENV}" >> .env
          echo "BOT_AUTH_TOKEN=${BOT_AUTH_TOKEN}" >> .env
          echo "BOT_USERNAME=${BOT_USERNAME}" >> .env
          echo "BOT_WEBHOOK_PORT=${BOT_WEBHOOK_PORT}" >> .env
          echo "BOT_WEBHOOK_URL=${BOT_WEBHOOK_URL}" >> .env
          echo "CLOUDFLARE_TOKEN_PROD=${CLOUDFLARE_TOKEN_PROD}" >> .env
          echo "KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}" >> .env
          echo "KAFKA_ITEM_NAMING_TOPIC=${KAFKA_ITEM_NAMING_TOPIC}" >> .env
          echo "MONGO_DB_DATABASE_NAME=${MONGO_DB_DATABASE_NAME}" >> .env
          echo "MONGO_DB_URI=${MONGO_DB_URI}" >> .env
          echo "MONGO_DB_USER=${MONGO_DB_USER}" >> .env
          echo "MONGO_DB_PASSWORD=${MONGO_DB_PASSWORD}" >> .env
      - name: Run Docker Compose
        run: cd ${{vars.WORK_DIR}} 
          && docker-compose --env-file .env up -d
      - name: Clean up environment file
        run: cd ${{vars.WORK_DIR}} && rm -f .env
