name: Deploy on push

on:
  push:
    branches: [ "master", "develop" ]

jobs:
  build-and-run:
    runs-on: self-hosted
    environment: ${{vars.ENV}}
    permissions:
      contents: read

    steps:
      - name: Update repository
        run : cd ${{vars.WORK_DIR}} && git fetch origin ${{ github.ref_name }} && git checkout && git pull
      - name: Set environment variables
        env:
          ENV: ${{vars.ENV}}
          JAVA_OPTIONS: ${JAVA_OPTIONS}
          BOT_AUTH_TOKEN: ${{ secrets.BOT_TOKEN }}
          BOT_USERNAME: ${{vars.BOT_USERNAME}}
          BOT_WEBHOOK_PORT: ${{vars.BOT_WEBHOOK_PORT}}
          BOT_WEBHOOK_URL: ${{vars.BOT_WEBHOOK_URL}}
          CLOUDFLARE_TOKEN: ${{secrets.CLOUDFLARE_TOKEN}}
          GRAFANA_USER: ${{secrets.GRAFANA_USER}}
          GRAFANA_PASSWORD: ${{secrets.GRAFANA_PASSWORD}}
          KAFKA_PORT: ${{vars.KAFKA_PORT}}
          KAFKA_ITEM_NAMING_TOPIC: ${{vars.KAFKA_ITEM_NAMING_TOPIC}}
          MONGO_DB_DATABASE_NAME: ${{vars.MONGO_DB_DATABASE_NAME}}
          MONGO_DB_PORT: ${{vars.MONGO_DB_PORT}}
          MONGO_DB_USER: ${{ secrets.MONGO_DB_USER }}
          MONGO_DB_PASSWORD: ${{ secrets.MONGO_DB_PASSWORD }}
        run: |
          cd ${{vars.WORK_DIR}} &&
          echo "ENV=${ENV}" >> .env
          echo "JAVA_OPTIONS=${JAVA_OPTIONS}" >> .env
          echo "BOT_AUTH_TOKEN=${BOT_AUTH_TOKEN}" >> .env
          echo "BOT_USERNAME=${BOT_USERNAME}" >> .env
          echo "BOT_WEBHOOK_PORT=${BOT_WEBHOOK_PORT}" >> .env
          echo "BOT_WEBHOOK_URL=${BOT_WEBHOOK_URL}" >> .env
          echo "CLOUDFLARE_TOKEN=${CLOUDFLARE_TOKEN}" >> .env
          echo "GRAFANA_USER=${GRAFANA_USER}" >> .env
          echo "GRAFANA_PASSWORD=${GRAFANA_PASSWORD}" >> .env
          echo "KAFKA_PORT=${KAFKA_PORT}" >> .env
          echo "KAFKA_ITEM_NAMING_TOPIC=${KAFKA_ITEM_NAMING_TOPIC}" >> .env
          echo "MONGO_DB_DATABASE_NAME=${MONGO_DB_DATABASE_NAME}" >> .env
          echo "MONGO_DB_PORT=${MONGO_DB_PORT}" >> .env
          echo "MONGO_DB_USER=${MONGO_DB_USER}" >> .env
          echo "MONGO_DB_PASSWORD=${MONGO_DB_PASSWORD}" >> .env
      - name: Run Shared services
        run: cd ${{vars.WORK_DIR}} &&
          docker-compose -f docker-compose.shared.yml --env-file .env up --build -d
      - name: Run Environment specific services
        run: cd ${{vars.WORK_DIR}} && 
          docker-compose --env-file .env up --build -d
      - name: Clean up environment file
        run: cd ${{vars.WORK_DIR}} && rm -f .env
      - name: Cleanup Docker Data
        run: docker system prune -af &&
          docker volume prune -f
      - name: Verify Cleanup
        run: docker system df
