name: Restart Shared Service

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Select branch to checkout"
        required: true
        type: choice
        options:
          # BEGIN BRANCH LIST
        - async-task-execution
        - codex/convert-game-results-to-balance-matrix
        - codex/group-threads-by-task-type-and-chatid
        - codex/introduce-single-consumer-for-asynctaskcompletionservice
        - develop
        - item-generation-refactoring
        - master
        - room-content-population
        - secure-test-environment
        - update-branch-list-15511882423
        - update-branch-list-12292818677
        - upgrade-gradle-dependencies
          # END BRANCH LIST
      service:
        description: "Select service to restart from docker-compose.shared.yml"
        required: true
        type: choice
        options:
          - loki
          - promtail
          - prometheus
          - grafana
          - mongodb-exporter
          - zookeeper
          - kafka
          - mongo
          - postgres

jobs:
  restart:
    runs-on: self-hosted
    environment:
      name: Restart
    steps:

      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}
          fetch-depth: 0
          persist-credentials: false
          clean: false

      - name: Set required environment variables
        run: |
          echo "ENV=${{vars.ENV}}" >> .env
          echo "GRAFANA_USER=${{secrets.GRAFANA_USER}}" >> .env
          echo "GRAFANA_PASSWORD=${{secrets.GRAFANA_PASSWORD}}" >> .env
          echo "KAFKA_PORT=${{vars.KAFKA_PORT}}" >> .env
          echo "MONGO_DB_PORT=${{vars.MONGO_DB_PORT}}" >> .env
          echo "MONGO_DB_USER=${{ secrets.MONGO_DB_USER }}" >> .env
          echo "MONGO_DB_PASSWORD=${{ secrets.MONGO_DB_PASSWORD }}" >> .env
          echo "MONGO_MONITORING_USER=${{ secrets.MONGO_MONITORING_USER }}" >> .env
          echo "MONGO_MONITORING_PASSWORD=${{ secrets.MONGO_MONITORING_PASSWORD }}" >> .env
          echo "POSTGRES_DATABASE_NAME=${{vars.POSTGRES_DATABASE_NAME}}" >> .env
          echo "POSTGRES_DATABASE_PASSWORD=${{secrets.POSTGRES_DATABASE_PASSWORD}}" >> .env
          echo "POSTGRES_DATABASE_USER=${{secrets.POSTGRES_DATABASE_USER}}" >> .env
          echo "POSTGRES_DATABASE_PORT=${{vars.POSTGRES_DATABASE_PORT}}" >> .env

      - name: Restart selected shared service
        run: |
          SERVICE="${{ github.event.inputs.service }}"
          echo "Stopping $SERVICE ..."
          docker-compose -p shared -f docker-compose.shared.yml --env-file .env stop "$SERVICE"
          echo "Starting $SERVICE ..."
          docker-compose -p shared -f docker-compose.shared.yml --env-file .env up "$SERVICE" --build -d

      - name: Clean up environment file
        run: rm -f .env

      - name: Remove unused containers and volumes
        run: |
          docker system prune -af &&
          docker volume prune -f

