name: Run tests

on:
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: self-hosted
    permissions:
      contents: read

    steps:
      - name: Update repository
        run : cd ${{vars.WORK_DIR}} && git fetch origin ${{ github.event.pull_request.head.ref }} &&
          git checkout && git pull

      - name: Run tests
        run: cd ${{vars.WORK_DIR}} &&
          docker build -f Dockerfile-test -t dungeon-prototype-app . &&
          docker run dungeon-prototype-app
      - name: Stop and remove container
        run: cd ${{vars.WORK_DIR}} &&
          docker stop && docker container rm dungeon-prototype-app