name: Run tests

on:
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  test:
    runs-on: self-hosted
    permissions:
      contents: read

    steps:
      - name: Configure Git Safe Directory
        run: |
          git config --global --add core.safeDirectory "$(pwd)"
          echo "Configured $(pwd) as a safe directory"
      - name: Update repository
        run : git fetch origin ${{ github.event.pull_request.head.ref }} &&
          git checkout && git pull

      - name: Run tests
        run: |
          docker build -f Dockerfile-test -t dungeon-prototype-app . &&
          docker run --rm dungeon-prototype-app

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
