name: Run tests

on:
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  test:
    runs-on: self-hosted
    permissions:
      contents: read

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          clean: false

      - name: Run tests
        run: |
          ci_env=`bash <(curl -s https://codecov.io/env)`
          docker build -f Dockerfile-test -t dungeon-prototype-app . &&
          docker run $ci_env -e CI=true --rm dungeon-prototype-app

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
