name: Run tests

on:
  pull_request:
    branches: [ "master", "develop" ]
    types:
      - opened
      - synchronize

jobs:
  test:
    runs-on: self-hosted
    environment:
      name: Test
    if: "${{ !contains(github.event.pull_request.labels.*.name, 'skip-check') }}"
    permissions:
      contents: read

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          clean: false

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Create coverage directory
        run: mkdir -p $(pwd)/coverage

      - name: Run tests
        run: |
          ci_env=`bash <(curl -s https://codecov.io/env)` \
          docker build -f Dockerfile-test -t dungeon-prototype-app . &&
          docker run $ci_env -e CI=true --rm \
          -v $(pwd)/coverage:/app/build/reports/jacoco/test \
          dungeon-prototype-app

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/jacocoTestReport.xml
          fail_ci_if_error: true

      - name: Cleanup Docker Data
        run: docker system prune -f &&
          docker volume prune -f
      - name: Verify Cleanup
        run: docker system df
