name: Update Deployment Workflow

on:
  create:
    branches:
      - '**'
  delete:
    branches:
      - '**'

jobs:
  update-workflow:
    runs-on: ubuntu-latest
    if: "! startsWith(github.ref_name, 'update-branch-list-')"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Configure Git User
        run: |
          git config --global user.email "arsnazarov94@gmail.com"
          git config --global user.name "Walrus94"

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Fetch Branch List
        id: fetch_branches
        run: |
          echo "Fetching branches..."
          BRANCHES=$(curl -s -H "Authorization: Bearer ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/branches | jq -r '.[].name')

          echo "Available branches:"
          echo "$BRANCHES"

          echo "BRANCH_OPTIONS<<EOF" >> $GITHUB_ENV
          echo "$BRANCHES" | sed 's/^/        - /' >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Update Deployment Workflow
        run: |
          echo -e "Branch options being used:\n${{ env.BRANCH_OPTIONS }}"
          echo "${{ env.BRANCH_OPTIONS }}" > branch_list.txt
          awk '
            BEGIN { inBlock = 0 }
            /# BEGIN BRANCH LIST/ { inBlock = 1; print; next }
            /# END BRANCH LIST/ { inBlock = 0; print; next }
            !inBlock { print }
            inBlock {
              while ((getline line < "branch_list.txt") > 0) {
                print line
              }
            }
          ' .github/workflows/deploy-to-test.yml > temp.yml
          mv temp.yml .github/workflows/deploy-to-test.yml
          
          awk '
            BEGIN { inBlock = 0 }
            /# BEGIN BRANCH LIST/ { inBlock = 1; print; next }
            /# END BRANCH LIST/ { inBlock = 0; print; next }
            !inBlock { print }
            inBlock {
              while ((getline line < "branch_list.txt") > 0) {
                print line
              }
            }
          ' .github/workflows/restart-shared-service.yml > temp.yml
          mv temp.yml .github/workflows/restart-shared-service.yml

      - name: Cleanup Temporary Files
        run: rm -f branch_list.txt

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          branch: update-branch-list-${{ github.run_id }}
          delete-branch: true
          title: "Update branch list"
          body: "Automatically updating branch list due to changes in repository."
          commit-message: "[auto] update branch list"
          base: master
          labels: |
            skip-check