name: Update Deployment Workflow

on:
#  create:
#    branches-ignore:
#      - 'update-branch-list-*'
#  delete:
#    branches-ignore:
#      - 'update-branch-list-*'
  workflow_dispatch:

jobs:
  update-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Configure Git User
        run: |
          git config --global user.email "arsnazarov94@gmail.com"
          git config --global user.name "Walrus94"

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Fetch Branch List
        id: fetch_branches
        run: |
          echo "Fetching branches..."
          BRANCHES=$(curl -s -H "Authorization: Bearer ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/branches | jq -r '.[].name')

          echo "Available branches:"
          echo "$BRANCHES"

          echo "BRANCH_OPTIONS<<EOF" >> $GITHUB_ENV
          echo "$BRANCHES" | sed 's/^/          - /' >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Update Deployment Workflow
        run: |
          echo -e "Branch options being used:\n${{ env.BRANCH_OPTIONS }}"
          echo "${{ env.BRANCH_OPTIONS }}" > branch_list.txt
          echo "branch_list.txt content:"
          cat branch_list.txt
          awk '
            BEGIN { inBlock = 0 }
            /# BEGIN BRANCH LIST/ { inBlock = 1; print; next }
            /# END BRANCH LIST/ { inBlock = 0; print; next }
            !inBlock { print }
            inBlock && /# BEGIN BRANCH LIST/ {
              while ((getline line < "branch_list.txt") > 0) {
                print line
              }
            }
          ' .github/workflows/deploy-to-test.yml > temp.yml
          echo "temp.yml content:"
          cat temp.yml
          mv temp.yml .github/workflows/deploy-to-test.yml

      - name: Cleanup Temporary Files
        run: rm -f branch_list.txt

      - name: Create a new branch
        run: |
          git checkout -b update-branch-list-${{ github.run_id }}
          git add .github/workflows/deploy-to-test.yml
          git commit -m "Update branch list dynamically"
          git push origin update-branch-list-${{ github.run_id }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          branch: update-branch-list-${{ github.run_id }}
          title: "Update branch list"
          body: "Automatically updating branch list due to changes in repository."
          base: master